schema = """
-- MySQL Script generated by MySQL Workbench
-- Wed Jul  9 21:21:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_schema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test_schema` ;

-- -----------------------------------------------------
-- Table `test_schema`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NOT NULL,
  `author` VARCHAR(128) NOT NULL,
  `isbn` VARCHAR(20) NULL DEFAULT NULL,
  `publisher` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`book_copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`book_copy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `edition` VARCHAR(64) NULL DEFAULT NULL,
  `copy_number` INT NOT NULL,
  `condition` VARCHAR(64) NULL DEFAULT NULL,
  `is_available` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `book_copy_ibfk_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `test_schema`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password_hash` VARCHAR(256) NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT NULL,
  `user_type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ix_user_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`borrow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_copy_id` INT NOT NULL,
  `borrower_id` INT NOT NULL,
  `lender_id` INT NOT NULL,
  `borrow_date` DATETIME NOT NULL DEFAULT now(),
  `due_date` DATETIME NOT NULL,
  `return_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `book_copy_id` (`book_copy_id` ASC) VISIBLE,
  INDEX `borrower_id` (`borrower_id` ASC) VISIBLE,
  INDEX `lender_id` (`lender_id` ASC) VISIBLE,
  CONSTRAINT `borrow_ibfk_1`
    FOREIGN KEY (`book_copy_id`)
    REFERENCES `test_schema`.`book_copy` (`id`),
  CONSTRAINT `borrow_ibfk_2`
    FOREIGN KEY (`borrower_id`)
    REFERENCES `test_schema`.`user` (`id`),
  CONSTRAINT `borrow_ibfk_3`
    FOREIGN KEY (`lender_id`)
    REFERENCES `test_schema`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`cliente` (
  `id` INT NOT NULL,
  `customer_type` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `test_schema`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(128) NOT NULL,
  `nome_fantasia` VARCHAR(128) NULL DEFAULT NULL,
  `numero_contato` VARCHAR(11) NULL DEFAULT NULL,
  `email_contato` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_schema`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_schema`.`funcionario` (
  `id` INT NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `test_schema`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
"""